[
  {
    clientId: "remarkable-measure-988440.framer.app",
    visitorId: "f4be3ecf-326f-4162-bf4b-ce4df41ce8e2",
    preferences: {
      analytics: true,
      marketing: true,
      personalization: true,
      action: "acceptance",
      bannerType: "gdpr",
    },
    policyVersion: "1.2",
    timestamp: "2025-10-06T18:26:11.495Z",
    country: "IN",
    bannerType: "gdpr",
    expiresAtTimestamp: 1770143171495,
    expirationDurationDays: 120,
    expectedCookies: [
      {
        name: "_ga",
        duration: "2 years",
        description:
          "Google Analytics: Used to distinguish unique users by assigning a randomly generated number as a client identifier.",
        toolname: "Google Analytics",
        dataCategory: null,
      },
      {
        name: "_gid",
        duration: "24 hours",
        description:
          "Google Analytics: Used to distinguish users and store information about how visitors use a website.",
        toolname: "Google Analytics",
        dataCategory: null,
      },
      {
        name: "_gat",
        duration: "1 minute",
        description:
          "Google Analytics: Used to throttle the request rate, limiting the collection of data on high traffic sites.",
        toolname: "Google Analytics",
        dataCategory: null,
      },
      {
        name: "_ga_*",
        duration: "session",
        description: "Cookie from unknown script",
        toolname: "Unknown",
        dataCategory: null,
      },
      {
        name: "_gac_*",
        duration: "session",
        description: "Cookie from unknown script",
        toolname: "Unknown",
        dataCategory: null,
      },
      {
        name: "essential_cookie",
        duration: "session",
        description: "Cookie from unknown script",
        toolname: "Unknown",
        dataCategory: null,
      },
      {
        name: "essential_cookie",
        duration: "session",
        description: "Cookie from unknown script",
        toolname: "Unknown",
        dataCategory: null,
      },
      {
        name: "essential_cookie",
        duration: "session",
        description: "Cookie from Essential,Personalization,Analytics script",
        toolname: "Essential,Personalization,Analytics",
        dataCategory: "Essential,Personalization,Analytics",
      },
      {
        name: "essential_cookie",
        duration: "session",
        description: "Cookie from unknown script",
        toolname: "Unknown",
        dataCategory: null,
      },
      {
        name: "session_id",
        duration: "session",
        description: "Essential session cookie for website functionality",
        toolname: "Essential",
        dataCategory: "essential",
      },
    ],
    metadata: {
      userAgent:
        "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Mobile Safari/537.36",
      language: "en-US",
      platform: "Android",
      timezone: "Asia/Calcutta",
      ip: "2401:4900:1c42:544d:48e2:8fa9:d040:ac94",
    },
  },
  {
    clientId: "remarkable-measure-988440.framer.app",
    visitorId: "075ae07a-8528-4ff3-a30c-43eab59ef620",
    preferences: {
      analytics: false,
      marketing: false,
      personalization: false,
      doNotShare: true,
      action: "rejection",
      bannerType: "gdpr",
    },
    policyVersion: "1.2",
    timestamp: "2025-10-06T21:36:45.348Z",
    country: "IN",
    bannerType: "gdpr",
    expiresAtTimestamp: 1770154605348,
    expirationDurationDays: 120,
    expectedCookies: [
      {
        name: "essential_cookie",
        duration: "session",
        description: "Cookie from unknown script",
        toolname: "Unknown",
        dataCategory: null,
      },
      {
        name: "essential_cookie",
        duration: "session",
        description: "Cookie from Essential,Personalization,Analytics script",
        toolname: "Essential,Personalization,Analytics",
        dataCategory: "Essential,Personalization,Analytics",
      },
      {
        name: "session_id",
        duration: "session",
        description: "Essential session cookie for website functionality",
        toolname: "Essential",
        dataCategory: "essential",
      },
    ],
    metadata: {
      language: "en-IN",
      platform: "Windows",
      timezone: "Asia/Calcutta",
      ip: "2401:4900:1c42:544d:48e2:8fa9:d040:ac94",
      userAgent:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36",
    },
  },
  {
    clientId: "remarkable-measure-988440.framer.app",
    visitorId: "8333de34-12ef-4d96-9918-4d45c946ea69",
    preferences: {
      analytics: true,
      marketing: true,
      personalization: true,
      action: "acceptance",
      bannerType: "gdpr",
    },
    policyVersion: "1.2",
    timestamp: "2025-10-07T19:00:27.178Z",
    country: "IN",
    bannerType: "gdpr",
    expiresAtTimestamp: 1772823627178,
    expirationDurationDays: 150,
    expectedCookies: [
      {
        name: "essential_cookie",
        duration: "session",
        description: "Cookie from unknown script",
        toolname: "Unknown",
        dataCategory: null,
      },
      {
        name: "essential_cookie",
        duration: "session",
        description: "Cookie from Essential,Personalization,Analytics script",
        toolname: "Essential,Personalization,Analytics",
        dataCategory: "Essential,Personalization,Analytics",
      },
      {
        name: "session_id",
        duration: "session",
        description: "Essential session cookie for website functionality",
        toolname: "Essential",
        dataCategory: "essential",
      },
    ],
    metadata: {
      userAgent:
        "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Mobile Safari/537.36 Edg/141.0.0.0",
      language: "en-US",
      platform: "Android",
      timezone: "Asia/Calcutta",
      ip: "2401:4900:1c45:28d0:547a:c9ea:68f6:a848",
    },
  },
];
